name = "NumDiff"
version = "1.8.2"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2016-2026, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran Numerical Differentiation Library"
homepage = "https://github.com/jacobwilliams/NumDiff"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[dev-dependencies]
pyplot-fortran = { git="https://github.com/jacobwilliams/pyplot-fortran.git", tag = "3.8.0" }
