compute_perturbation_vector – NumDiff
compute_perturbation_vector Subroutine
8 statements
Source File
private subroutine compute_perturbation_vector(me, x, dx)
Compute dx, the perturbation vector for x used when computing the gradients.
Type Bound
numdiff_type
Arguments
Type Intent Optional Attributes Name
class(numdiff_type), intent(inout) :: me
real(kind=wp), intent(in), dimension(me%n) :: x
vector of variables (size n)
real(kind=wp), intent(out), dimension(me%n) :: dx
absolute perturbation (>0) for each variable
Calls
Called by
Source Code
    subroutine compute_perturbation_vector(me,x,dx)
    implicit none
    class(numdiff_type),intent(inout)    :: me
    real(wp),dimension(me%n),intent(in)  :: x  !! vector of variables (size `n`)
    real(wp),dimension(me%n),intent(out) :: dx !! absolute perturbation (>0)
                                               !! for each variable
    if (me%exception_raised) return ! check for exceptions
    call me%compute_perturb_vector(x,me%dpert,me%perturb_mode,dx)
    end subroutine compute_perturbation_vector
Call graph
compute_perturbation_vector calls compute_perturb_vector
compute_perturb_vector calls raise_exception
compute_jacobian calls compute_perturbation_vector
compute_jacobian_dense calls compute_jacobian
compute_jacobian_times_vector calls compute_jacobian