compute_indices – NumDiff
compute_indices Subroutine
9 statements
Source File
private subroutine compute_indices(me)
Computes the indices vector in the class.
Type Bound
sparsity_pattern
Arguments
Type Intent Optional Attributes Name
class(sparsity_pattern), intent(inout) :: me
Called by
Source Code
    subroutine compute_indices(me)
    implicit none
    class(sparsity_pattern),intent(inout) :: me
    integer :: i !! counter
    allocate(me%indices(me%num_nonzero_elements))
    !me%indices = [(i,i=1,me%num_nonzero_elements)]
    do i = 1, me%num_nonzero_elements
        me%indices(i) = i
    end do
    end subroutine compute_indices
Call graph
compute_sparsity_dense calls compute_indices
compute_sparsity_random calls compute_indices
compute_sparsity_random_2 calls compute_indices
set_sparsity_pattern calls compute_indices