destroy_sparsity_pattern – NumDiff
destroy_sparsity_pattern Subroutine
5 statements
Source File
private subroutine destroy_sparsity_pattern(me)
Destroy the sparsity pattern in the class.
Type Bound
numdiff_type
Arguments
Type Intent Optional Attributes Name
class(numdiff_type), intent(inout) :: me
Calls
Called by
Source Code
    subroutine destroy_sparsity_pattern(me)
    implicit none
    class(numdiff_type),intent(inout) :: me
    call me%sparsity%destroy()
    end subroutine destroy_sparsity_pattern
Call graph
destroy_sparsity_pattern calls destroy_sparsity
compute_sparsity_dense calls destroy_sparsity_pattern
compute_sparsity_random calls destroy_sparsity_pattern
compute_sparsity_random_2 calls destroy_sparsity_pattern
set_sparsity_pattern calls destroy_sparsity_pattern