dsm_wrapper – NumDiff
dsm_wrapper Subroutine
18 statements
Source File
private subroutine dsm_wrapper(me, n, m, info)
Wrapper for dsm to compute the sparsity pattern partition.
Type Bound
sparsity_pattern
Arguments
Type Intent Optional Attributes Name
class(sparsity_pattern), intent(inout) :: me
integer, intent(in) :: n
number of columns of jacobian matrix
integer, intent(in) :: m
number of rows of jacobian matrix
integer, intent(out) :: info
status output from dsm
Calls
Called by
Source Code
    subroutine dsm_wrapper(me,n,m,info)
    implicit none
    class(sparsity_pattern),intent(inout) :: me
    integer,intent(in)  :: n     !! number of columns of jacobian matrix
    integer,intent(in)  :: m     !! number of rows of jacobian matrix
    integer,intent(out) :: info  !! status output from [[dsm]]
    integer :: mingrp !! for call to [[dsm]]
    integer,dimension(:),allocatable :: ipntr  !! for call to [[dsm]]
    integer,dimension(:),allocatable :: jpntr  !! for call to [[dsm]]
    integer,dimension(:),allocatable :: irow   !! for call to [[dsm]]
                                               !! (temp copy since [[dsm]]
                                               !! will modify it)
    integer,dimension(:),allocatable :: icol   !! for call to [[dsm]]
                                               !! (temp copy since [[dsm]]
                                               !! will modify it)
    allocate(ipntr(m+1))
    allocate(jpntr(n+1))
    allocate(me%ngrp(n))
    irow = me%irow
    icol = me%icol
    call dsm(m,n,me%num_nonzero_elements,&
             irow,icol,&
             me%ngrp,me%maxgrp,&
             mingrp,info,ipntr,jpntr)
    end subroutine dsm_wrapper
Call graph
dsm_wrapper calls dsm
dsm calls degr, ido, numsrt, seq, setr, slo, srtdat
ido calls numsrt
compute_sparsity_random calls dsm_wrapper
compute_sparsity_random_2 calls dsm_wrapper
set_sparsity_pattern calls dsm_wrapper