expand_vector_real – NumDiff
expand_vector_real Subroutine
31 statements
Source File
private pure subroutine expand_vector_real(vec, n, chunk_size, val, finished)
Add elements to the real vector in chunks.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:), allocatable :: vec
integer, intent(inout) :: n
counter for last element added to vec. must be initialized to size(vec) (or 0 if not allocated) before first call
integer, intent(in) :: chunk_size
allocate vec in blocks of this size (>0)
real(kind=wp), intent(in), optional :: val
the value to add to vec
logical, intent(in), optional :: finished
set to true to return vec as its correct size (n)
Called by
Source Code
    pure subroutine expand_vector_real(vec,n,chunk_size,val,finished)
    implicit none
    real(wp),dimension(:),allocatable,intent(inout) :: vec
    integer,intent(inout)       :: n           !! counter for last element added to `vec`.
                                               !! must be initialized to `size(vec)`
                                               !! (or 0 if not allocated) before first call
    integer,intent(in)          :: chunk_size  !! allocate `vec` in blocks of this size (>0)
    real(wp),intent(in),optional :: val        !! the value to add to `vec`
    logical,intent(in),optional :: finished    !! set to true to return `vec`
                                               !! as its correct size (`n`)
    real(wp),dimension(:),allocatable :: tmp  !! temporary array
    if (present(val)) then
        if (allocated(vec)) then
            if (n==size(vec)) then
                ! have to add another chunk:
                allocate(tmp(size(vec)+chunk_size))
                tmp(1:size(vec)) = vec
                call move_alloc(tmp,vec)
            end if
            n = n + 1
        else
            ! the first element:
            allocate(vec(chunk_size))
            n = 1
        end if
        vec(n) = val
    end if
    if (present(finished)) then
        if (finished) then
            ! set vec to actual size (n):
            if (allocated(tmp)) deallocate(tmp)
            allocate(tmp(n))
            tmp = vec(1:n)
            call move_alloc(tmp,vec)
        end if
    end if
    end subroutine expand_vector_real
Call graph
expand_vector calls expand_vector_real
compute_sparsity_random calls expand_vector, resize_sparsity_vectors
compute_sparsity_random_2 calls expand_vector, resize_sparsity_vectors, divide_interval
resize_sparsity_vectors calls expand_vector
unique_int calls expand_vector
unique_real calls expand_vector
unique calls unique_int, unique_real
divide_interval calls unique
put_in_cache calls unique
compute_function_with_cache calls put_in_cache