swap_real – NumDiff
swap_real Subroutine
9 statements
Source File
private pure elemental subroutine swap_real(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout) :: i1
real(kind=wp), intent(inout) :: i2
Called by
Source Code
    pure elemental subroutine swap_real(i1,i2)
    implicit none
    real(wp),intent(inout) :: i1
    real(wp),intent(inout) :: i2
    real(wp) :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap_real
Call graph
swap calls swap_real
sort_ascending_int calls swap
sort_ascending_real calls swap
sort_ascending calls sort_ascending_int, sort_ascending_real
unique_int calls sort_ascending
unique_real calls sort_ascending
unique calls unique_int, unique_real
divide_interval calls unique
put_in_cache calls unique
compute_function_with_cache calls put_in_cache
compute_sparsity_random_2 calls divide_interval