expand_vector – NumDiff
expand_vector Interface
3 statements
Source File
public interface expand_vector
Calls
Called by
Module Procedures
private pure subroutine expand_vector_int(vec, n, chunk_size, val, finished)
Add elements to the integer vector in chunks.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:), allocatable :: vec
integer, intent(inout) :: n
counter for last element added to vec. must be initialized to size(vec) (or 0 if not allocated) before first call
integer, intent(in) :: chunk_size
allocate vec in blocks of this size (>0)
integer, intent(in), optional :: val
the value to add to vec
logical, intent(in), optional :: finished
set to true to return vec as its correct size (n)
private pure subroutine expand_vector_real(vec, n, chunk_size, val, finished)
Add elements to the real vector in chunks.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:), allocatable :: vec
integer, intent(inout) :: n
counter for last element added to vec. must be initialized to size(vec) (or 0 if not allocated) before first call
integer, intent(in) :: chunk_size
allocate vec in blocks of this size (>0)
real(kind=wp), intent(in), optional :: val
the value to add to vec
logical, intent(in), optional :: finished
set to true to return vec as its correct size (n)
Call graph
expand_vector calls expand_vector_int, expand_vector_real
compute_sparsity_random calls expand_vector, resize_sparsity_vectors
compute_sparsity_random_2 calls expand_vector, resize_sparsity_vectors, divide_interval
resize_sparsity_vectors calls expand_vector
unique_int calls expand_vector
unique_real calls expand_vector
unique calls unique_int, unique_real
divide_interval calls unique
put_in_cache calls unique
compute_function_with_cache calls put_in_cache