finite_diff_method – NumDiff
finite_diff_method Interface
3 statements
Source File
private interface finite_diff_method
constructor
Calls
Called by
Contents
Module Procedures
initialize_finite_difference_method
Module Procedures
private function initialize_finite_difference_method(id, name, class, dx_factors, df_factors, df_den_factor) result(me)
Constructor for a finite_diff_method.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
unique ID for the method
character(len=*), intent(in) :: name
the name of the method
integer, intent(in) :: class
2=backward diffs, 3=central diffs, etc...
integer, intent(in), dimension(:) :: dx_factors
multiplicative factors for dx perturbation
integer, intent(in), dimension(:) :: df_factors
multiplicative factors for accumulating function evaluations
integer, intent(in) :: df_den_factor
denominator factor for finite difference equation (times dx)
Return Value type(finite_diff_method)
Call graph
finite_diff_method calls initialize_finite_difference_method
get_finite_difference_method calls finite_diff_method
get_all_methods_in_class calls get_finite_difference_method
initialize_numdiff calls get_finite_difference_method, get_all_methods_in_class
get_finite_diff_formula calls get_finite_difference_method
compute_sparsity_random_2 calls get_all_methods_in_class