unique – NumDiff
unique Interface
3 statements
Source File
public interface unique
Calls
Called by
Module Procedures
private function unique_int(vec, chunk_size) result(ivec_unique)
Returns only the unique elements of the vector (sorted in ascending order).
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: vec
a vector of integers
integer, intent(in) :: chunk_size
chunk size for adding to arrays
Return Value integer, dimension(:), allocatable
unique elements of ivec
private function unique_real(vec, chunk_size) result(ivec_unique)
Returns only the unique elements of the vector (sorted in ascending order).
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: vec
a vector of integers
integer, intent(in) :: chunk_size
chunk size for adding to arrays
Return Value real(kind=wp), dimension(:), allocatable
unique elements of ivec
Call graph
unique calls unique_int, unique_real
unique_int calls expand_vector, sort_ascending
unique_real calls expand_vector, sort_ascending
expand_vector calls expand_vector_int, expand_vector_real
sort_ascending calls sort_ascending_int, sort_ascending_real
sort_ascending_int calls swap
sort_ascending_real calls swap
swap calls swap_int, swap_real
divide_interval calls unique
put_in_cache calls unique
compute_function_with_cache calls put_in_cache
compute_sparsity_random_2 calls divide_interval